name: Code Review

on: [pull_request]

jobs:

  terraform-fmt:
    name: terraform fmt

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/filiptepper/checkcheckcheck:latest

    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: terraform fmt
        uses: filiptepper/github-action@main
